export enum TypeNotification {
  METEO = 'METEO',
  ALERTE_MALADIE = 'ALERTE_MALADIE',
  ALERTE_RAVAGEUR = 'ALERTE_RAVAGEUR',
  CONSEIL_AGRICOLE = 'CONSEIL_AGRICOLE',
  RAPPEL_ACTIVITE = 'RAPPEL_ACTIVITE',
  SYSTEME = 'SYSTEME'
}
