export enum TypeActivite {
  PREPARATION_SOL = 'PREPARATION_SOL',
  SEMIS = 'SEMIS',
  IRRIGATION = 'IRRIGATION',
  APPLICATION_ENGRAIS = 'APPLICATION_ENGRAIS',
  TRAITEMENT_PHYTOSANITAIRE = 'TRAITEMENT_PHYTOSANITAIRE',
  DESHERBAGE = 'DESHERBAGE',
  RECOLTE = 'RECOLTE',
  AUTRE = 'AUTRE'
}
